name: Build Translator EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # 使用一个稳定版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 speechrecognition simpleaudio google-generativeai pydub pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --onefile --noconsole --icon=icon.ico --hidden-import "PyQt6.QtWidgets" --hidden-import "PyQt6.QtCore" translator.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: translator-exe
        path: dist/translator.exe
